# This is a basic workflow that is manually triggered

name: check update

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push: 
    branches:
      - main
  schedule:
    - cron: "0 */8 * * *"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  check:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      
    - name: get hash
      run: curl https://raw.githubusercontent.com/Hexxeh/rpi-firmware/master/git_hash > git_hash
    - name: git update
      run: git submodule update --init --recursive --depth 5
    - name: git checkout
      run: cd linux && git submodule update --remote && git checkout $(cat git_hash)
    
    - name: Commit changes
      uses: EndBug/add-and-commit@v7
      with:
        author_name: github-actions
        author_email: 41898282+github-actions[bot]@users.noreply.github.com
